-- Which-key for keybinding help
return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    preset = "modern",
  },
  config = function()
    local wk = require("which-key")
    wk.add({
      { "<leader>a", group = "Align" },
      { "<leader>f", group = "Find" },
      { "<leader>ff", desc = "Find Files" },
      { "<leader>fg", desc = "Live Grep" },
      { "<leader>fb", desc = "Buffers" },
      { "<leader>fh", desc = "Help Tags" },
      { "<leader>fd", desc = "Diagnostics" },
      { "<leader>e", desc = "Toggle file tree" },
      { "<leader>v", desc = "Edit config" },
      { "<leader>b", group = "Buffer" },
      { "<leader>bn", desc = "Next buffer" },
      { "<leader>bp", desc = "Previous buffer" },
      { "<leader>bx", desc = "Close current buffer" },
      { "<leader>bc", desc = "Create new buffer" },
      { "<leader>bX", desc = "Close other buffers" },
      { "<leader>bb", desc = "Pick buffer" },
      { "<leader>b<", desc = "Move buffer left" },
      { "<leader>b>", desc = "Move buffer right" },
      { "<leader>c", group = "Code" },
      { "<leader>ca", desc = "Code Action" },
      { "<leader>r", group = "LSP" },
      { "<leader>rn", desc = "Rename" },
      { "<leader>g", group = "Git" },
      { "<leader>gg", desc = "LazyGit" },
      { "<leader>gp", desc = "Preview git hunk" },
      { "<leader>gr", desc = "Reset git hunk" },
      { "<leader>w", desc = "Pick a window" },
      { "<leader>m", group = "Markdown" },
      { "<leader>mp", desc = "Markdown Preview Start" },
      { "<leader>ms", desc = "Markdown Preview Stop" },
      { "]c", desc = "Next git change" },
      { "[c", desc = "Previous git change" },
      { "<leader>h", function() wk.show({ global = true }) end, desc = "Show All Keybindings" },
      { "<C-g>", desc = "Git Status" },
      { "<F1>", desc = "Toggle Precognition" },
      { "<F2>", desc = "Toggle Paste Mode" },
      { "<F3>", desc = "Toggle Hardtime" },
      { "<Space>", desc = "Toggle Fold" },
      { "K", desc = "Hover Documentation" },
      { "gd", desc = "Go to Definition" },
      { "gr", desc = "References" },
    })
  end,
}
