# Espanso main configuration
show_notifications: false
auto_restart: true
preserve_clipboard: true
restore_clipboard: 1000

# Backend configuration - auto detects best method
backend: auto

# Keyboard layout (fixes warning)  
keyboard_layout:
  layout: "us"

# Use clipboard injection to avoid input device conflicts with kanata
clipboard_threshold: 100
inject_delay: 10

# Search parameters
# search_trigger: ";"
search_shortcut: "ALT+SPACE"

# Undo key
undo_backspace: true
